title: 'Bamboo B&B Roma'
default_lang: en
author:
  name: 'Andrea Terzani'
  email: booking@bambooroma.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Sleep in Rome between Trastevere and the Vatican city'
  Keywords: 'Roma,Bamboo,Hotel'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
