title: 'Bamboo B&B Roma'
default_lang: en
author:
  name: 'Andrea Terzani'
  email: booking@bambooroma.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Bamboo isn''t only a B&B, it''s rather a lifestyle. Bamboo is a clean luxury place at green prices. Bamboo is “green” like our avatar Puck, and is located in the centre of Rome.'
  Keywords: 'Roma,Bamboo,Hotel'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
